#GET http://localhost:9092/api/activities/activities
#X-User-ID: bebd9bac-0540-415d-a314-41ec8306f9b6

#through api-gateway
GET http://localhost:9090/api/activities/activities
X-User-ID: bebd9bac-0540-415d-a314-41ec8306f9b6