server:
  port: 9095

spring:
  application:
    name: config-server

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config #to load all the config from this folder
